### ISSUE TITLE
Fix deploy of functions from Mac Pro

### ISSUE THREAD

**Issue by jkomoros** [jkomoros/card-web#650]
firebase functions deploying isn't working. f3aeba0c5766af4bd9020afe116a7187be6af946 was partially an attempt to fix but still not working.

```
Build failed: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> protobufjs@6.8.8 postinstall /workspace/node_modules/protobufjs
> node scripts/postinstall


> puppeteer@19.4.1 postinstall /workspace/node_modules/puppeteer
> node install.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'puppeteer/internal/node/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/workspace/node_modules/puppeteer/install.js:38:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@19.4.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@19.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2023-01-02T16_20_01_234Z-debug.log; Error ID: 49341d49

Functions deploy had errors with the following functions:
	autoTweet(us-central1)
	emailAdminOnMessage(us-central1)
	emailAdminOnStar(us-central1)
	fetchTweetEngagement(us-central1)
	legal(us-central1)
	screenshot(us-central1)
i  functions: cleaning up build files...
Error: There was an error deploying functions:
- Error Failed to update function autoTweet in region us-central1
- Error Failed to update function screenshot in region us-central1
- Error Failed to update function fetchTweetEngagement in region us-central1
- Error Failed to update function legal in region us-central1
- Error Failed to update function emailAdminOnMessage in region us-central1
- Error Failed to update function emailAdminOnStar in region us-central1
```

**Comment by jkomoros** [comment]
Perhaps an old node_version for firebase functions?

**Comment by jkomoros** [comment]
#638 is likely related
